image: "gableroux/unity:latest"

stages:
  - test
  - build

.test: &test
  stage: test
  before_script:
    - mkdir -p /root/.cache/unity3d
  script:
    - xvfb-run --server-args="-screen 0 1024x768x24" /opt/Unity/Editor/Unity -projectPath $(pwd) -batchmode -runTests -force-opengl -logFile -testResults $(pwd)/$TEST_PLATFORM-results.xml -testPlatform $TEST_PLATFORM

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

test-playmode:
  <<: *test
  variables:
    TEST_PLATFORM: playmode

.build: &build
  stage: build
  before_script:
    - mkdir builds
  script:
    - echo "todo: run build for $BUILD_TARGET"
    # - xvfb-run --server-args="-screen 0 1024x768x24" /opt/Unity/Editor/Unity unity -projectPath $(pwd) -quit -batchmode -buildTarget $BUILD_TARGET -customBuildTarget $BUILD_TARGET -customBuildPath "./builds/StandaloneLinux64" -customBuildOptions AcceptExternalModificationsToPlayer -executeMethod BuildCommand.PerformBuild -logFile
  only:
    - master

build-StandaloneLinux64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneLinux64

build-StandaloneOSXUniversal:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneOSXUniversal

build-StandaloneWindows64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneWindows64
